import React, { useEffect, useState } from 'react';
import { Plus, X } from 'lucide-react';
import { api } from '../services/api';
const emptyForm={facultyName:'',facultyEmail:'',facultyInstitution:'',facultyDepartment:'',facultyDesignation:'',relationshipToStudent:'',coursesTaught:'',purpose:'',studentMessage:'',deadline:''};
const badge={pending:'bg-amber-50 text-amber-700',accepted:'bg-emerald-50 text-emerald-700',declined:'bg-red-50 text-red-600',cancelled:'bg-gray-100 text-gray-500'};
export default function Recommendations(){
 const [items,setItems]=useState([]),[open,setOpen]=useState(false),[form,setForm]=useState(emptyForm),[error,setError]=useState('');
 const load=()=>api.getStudentRecommendations().then(setItems).catch(e=>setError(e.message)); useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();setError('');try{await api.createRecommendation(form);setForm(emptyForm);setOpen(false);load()}catch(err){setError(err.message)}};
 const cancel=async id=>{if(!window.confirm('Cancel this pending request?'))return;await api.cancelRecommendation(id);load()};
 return <div className="xl:col-span-3 space-y-6"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-extrabold">Recommendations</h2><p className="text-sm text-gray-500">Request, track, and download faculty recommendation letters.</p></div><button onClick={()=>setOpen(true)} className="flex items-center gap-2 px-4 py-3 bg-brandBlue text-white rounded-xl font-bold text-sm"><Plus size={17}/> Request Recommendation</button></div>{error&&<div className="p-3 bg-red-50 text-red-600 rounded-xl text-sm">{error}</div>}<div className="bg-white border rounded-3xl overflow-x-auto"><table className="w-full text-sm"><thead className="bg-brandPaleBlue text-left"><tr>{['Faculty','Institution','Purpose','Deadline','Status','Created','Letter'].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{items.map(r=><tr className="border-t" key={r.id}><td className="p-4"><b>{r.facultyName}</b><div className="text-xs text-gray-500">{r.facultyEmail}</div></td><td className="p-4">{r.facultyInstitution||'—'}</td><td className="p-4">{r.purpose}</td><td className="p-4">{r.deadline?.slice(0,10)}</td><td className="p-4"><span className={`px-3 py-1 rounded-full text-xs font-bold capitalize ${badge[r.status]}`}>{r.status}</span></td><td className="p-4 text-gray-500">{new Date(r.createdAt).toLocaleDateString()}</td><td className="p-4">{r.status==='pending'&&<button onClick={()=>cancel(r.id)} className="text-red-500 font-bold">Cancel</button>}{r.submittedAt&&<button onClick={()=>api.downloadRecommendationLetter(r.id,r.letterFileName)} className="text-brandBlue font-bold">Download letter</button>}{r.status==='accepted'&&!r.submittedAt&&<span className="text-xs text-gray-400">Awaiting letter</span>}</td></tr>)}</tbody></table>{!items.length&&<p className="p-12 text-center text-gray-400">No recommendation requests yet.</p>}</div>{open&&<div className="fixed inset-0 bg-black/50 z-50 overflow-y-auto p-6"><form onSubmit={submit} className="max-w-2xl mx-auto bg-white rounded-3xl p-7 space-y-4"><div className="flex justify-between"><h3 className="text-xl font-bold">Request Recommendation</h3><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="grid md:grid-cols-2 gap-4">{Object.keys(emptyForm).map(key=><label className={key==='studentMessage'?'md:col-span-2 text-xs font-bold':'text-xs font-bold'} key={key}>{key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}<input type={key==='facultyEmail'?'email':key==='deadline'?'date':'text'} required={['facultyName','facultyEmail','relationshipToStudent','purpose','deadline'].includes(key)} min={key==='deadline'?new Date(Date.now()+86400000).toISOString().slice(0,10):undefined} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-1 w-full border rounded-xl p-3 font-normal"/></label>)}</div><button className="w-full bg-brandBlue text-white rounded-xl p-3 font-bold">Send Request</button></form></div>}</div>;
}
