const fs=require('fs'); const path=require('path'); const assert=require('assert');
process.env.DB_HOST='127.0.0.1'; process.env.DB_USER='uniscout_test_no_mysql'; process.env.DB_PASSWORD='invalid'; process.env.JWT_SECRET='test-only-secret';
const dbFile=path.join(__dirname,'../data/local_db.json'); const backup=fs.existsSync(dbFile)?fs.readFileSync(dbFile):null;
const clean={users:[],verification_tokens:[],student_profiles:[],recommendation_requests:[]}; fs.writeFileSync(dbFile,JSON.stringify(clean));
const db=require('../config/db'); const auth=require('../controllers/authController'); const rec=require('../controllers/recommendationController'); const middleware=require('../middleware/authMiddleware');
const response=()=>({statusCode:200,body:null,status(n){this.statusCode=n;return this},json(v){this.body=v;return this}});
async function call(fn,req){const res=response();await fn(req,res);return res}
(async()=>{try{await db.initializeDb();
 let data=JSON.parse(fs.readFileSync(dbFile)); data.users.push({id:1,fullName:'Faculty Test',email:'faculty@test.edu',password:'password123',role:'Faculty',email_verified:true,isVerified:true,isBlocked:false,institution:'Test U',department:'CS',designation:'Professor'}); fs.writeFileSync(dbFile,JSON.stringify(data));
 const faculty=data.users.find(u=>u.role==='Faculty');
 const facultyLogin=await call(auth.login,{body:{email:'faculty@test.edu',password:'password123',role:'Faculty'}}); assert.equal(facultyLogin.statusCode,200,'faculty login');
 const student={id:2,fullName:'Student Test',email:'student@test.edu',role:'Student'}; const facultyUser={id:faculty.id,fullName:faculty.fullName,email:'faculty@test.edu',role:'Faculty'}; const other={id:3,email:'other@test.edu',role:'Faculty'};
 const deadline=new Date(Date.now()+10*86400000).toISOString().slice(0,10); const body={facultyName:'Faculty Test',facultyEmail:'FACULTY@test.edu',relationshipToStudent:'Teacher',purpose:'Graduate admission',deadline};
 const created=await call(rec.create,{user:student,body}); assert.equal(created.statusCode,201,'student creates request'); const id=created.body.recommendation.id;
 assert.equal((await call(rec.create,{user:student,body})).statusCode,400,'duplicate pending rejected');
 assert.equal((await call(rec.create,{user:facultyUser,body})).statusCode,403,'faculty cannot create');
 assert.equal((await call(rec.listFaculty,{user:facultyUser})).body.recommendations.length,1,'correct faculty sees request');
 assert.equal((await call(rec.listFaculty,{user:other})).body.recommendations.length,0,'unrelated faculty cannot see request');
 assert.equal((await call(rec.accept,{user:student,params:{id}})).statusCode,403,'student cannot accept');
 assert.equal((await call(rec.accept,{user:other,params:{id}})).statusCode,403,'unrelated faculty cannot update');
 assert.equal((await call(rec.accept,{user:facultyUser,params:{id}})).body.recommendation.status,'accepted','faculty accepts');
 assert.equal((await call(rec.cancel,{user:student,params:{id}})).statusCode,400,'accepted request cannot be cancelled');
 assert.equal((await call(rec.listStudent,{user:student})).body.recommendations[0].status,'accepted','student sees accepted status');
 const second=await call(rec.create,{user:student,body:{...body,purpose:'Scholarship'}}); const id2=second.body.recommendation.id;
 assert.equal((await call(rec.decline,{user:facultyUser,params:{id:id2}})).body.recommendation.status,'declined','faculty declines');
 const third=await call(rec.create,{user:student,body:{...body,purpose:'Internship'}}); const id3=third.body.recommendation.id;
 assert.equal((await call(rec.cancel,{user:student,params:{id:id3}})).body.recommendation.status,'cancelled','student cancels pending');
 assert.equal((await call(rec.accept,{user:facultyUser,params:{id:id3}})).statusCode,400,'faculty cannot accept cancelled');
 const unauth=response(); middleware({headers:{}},unauth,()=>{}); assert.equal(unauth.statusCode,401,'unauthenticated request rejected');
 console.log('15 recommendation/auth integration assertions passed.');
}finally{if(backup)fs.writeFileSync(dbFile,backup);else fs.unlinkSync(dbFile)}})().catch(e=>{console.error(e);process.exitCode=1});
